-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TuitionSession" ALTER COLUMN "durationMinutes" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "totalMoney" SET DATA TYPE DECIMAL(65,30);
